#!/bin/bash
# Remove unused files from web-scraper directory
# Generated by analyze_unused_files.py

cd /home/bihac-danas/web-scraper

echo "Removing unused files..."
rm -v "dzbinac.py"
rm -v "klix_feed.py"
rm -v "komrad-bihac.py"
rm -v "dzbihac_state.json"
rm -v "komrad_bihac_state.json"
rm -v "oslobodjenje_rss_state.json"
rm -v "rss_import_state.json"
rm -v "debug_api.py"
rm -v "debug_oslobodjenje.py"
rm -v "debug_search.html"
rm -v "debug_soup.html"
rm -v "deleteme"
# rm -v "analyze_unused_files.py"  # Keep this - useful analysis tool
rm -v "check_bihac_articles.py"
rm -v "dashboard_backup.py"
rm -v "oslobodjenje.py"
rm -v "oslobodjenje_feed.py"
rm -v "update_all_scrapers_source.py"
rm -v "search_page_snippet.html"
rm -v "klix_news.txt"

echo ""
echo "Done! Removed 19 files."
